### PR TITLE
Add CI workflows for standard checks, linting, and test coverage

### PR DESCRIPTION
**Pull request by taylorreiter**
Following https://github.com/r-lib/actions/tree/v2-branch/examples#example-workflows
Set up using:

```
usethis::use_github_action("check-standard")
usethis::use_github_action("test-coverage")
```

there were LOTS of problems that I didn't know about. First of all, I've been using `test()` locally to make sure my tests pass before I push something to github. I should have been running `check()` which runs the tests and lots of other things to look for problems in the code. Some problems that `check()` found were:
+ the use of `.` in tidyverse pipe functions. I removed a few of these and temporarily kept on for one line of code that was particularly trick to come up with originally and I wasn't sure how to replace yet.
+ the use of `.data$` to call variables used by tidyverse, or `""` when that variable was called by `tidyselect()`.
+ missing parameter docs
+ use of other global vars
+ missing package exports (tibble, stats)

I also switched the majority of examples to not run. eventually I want to add a bunch of data to the package to demonstrate the examples, but I need to learn best practices for that first, so that will be a separate PR.

### CODE REVIEW

**Comment by taylorreiter** [comment]
I removed `lint` and `test-coverage` because they fail with `x Failed to build source package 'XML' `. I tried adding `any::XML` but that didn't fix the issue. I'll revisit that after I get the other tests passing.

https://github.com/r-lib/actions/issues/559

**Comment by taylorreiter** [comment]
macOS, windows, and ubuntu-lastest (oldrel-1) are all passing, but ubuntu-latest (devel) and (release) both fail with the xml error. Things I'm trying:

+ didn't work:
```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::XML
          extra-packages: any::rcmdcheck
          needs: check
```
+ didn't work:
```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::XML, any::rcmdcheck
          needs: check
```

**Comment by taylorreiter** [comment]
```
sourmashconsumr Coverage: 77.97%
R/plot_compare.R: 68.97%
R/metacoder.R: 73.53%
R/plot_signatures.R: 82.28%
R/read_sourmash_outputs.R: 82.35%
```

**Review by elizabethmcd — APPROVED** [review]
LGTM - excited to see the CI working!

**Pull request merged**
